# Generated by Django 3.2 on 2021-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='问题')),
                ('desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'system_questions',
            },
        ),
    ]
