# Generated by Django 3.2 on 2021-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210604_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
