# Generated by Django 3.2 on 2021-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_questions_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-number'], 'verbose_name': '常见问题', 'verbose_name_plural': '常见问题'},
        ),
        migrations.AddField(
            model_name='questions',
            name='number',
            field=models.SmallIntegerField(default=1, help_text='数字越大越靠前', verbose_name='编号'),
        ),
    ]
