# Generated by Django 3.2 on 2021-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210604_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['number'], 'verbose_name': '常见问题', 'verbose_name_plural': '常见问题'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='reorder',
        ),
        migrations.AddField(
            model_name='slider',
            name='number',
            field=models.SmallIntegerField(default=0, help_text='默认为升序排列', verbose_name='排序字段'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='number',
            field=models.SmallIntegerField(default=1, help_text='默认为升序排列', verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(max_length=255, upload_to='slider', verbose_name='图片地址'),
        ),
    ]
