# Generated by Django 3.2 on 2021-06-04 12:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpeg', null=True, upload_to=accounts.models.set_avatar, verbose_name='用户头像'),
        ),
    ]
