# Generated by Django 3.2 on 2021-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='target_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='score',
            field=models.FloatField(default=5, verbose_name='评分'),
        ),
    ]
