# Generated by Django 3.2 on 2021-06-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_artwork_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-love_counts', '-created_at'], 'verbose_name': '评论及回复', 'verbose_name_plural': '评论及回复'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='love_count',
            new_name='love_counts',
        ),
        migrations.AddField(
            model_name='artwork',
            name='love_counts',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
        migrations.DeleteModel(
            name='LoveCount',
        ),
    ]
