# Generated by Django 3.2 on 2021-06-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20210611_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-love_counts'], 'verbose_name': '作品表', 'verbose_name_plural': '作品表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '评论及回复', 'verbose_name_plural': '评论及回复'},
        ),
    ]
